### ISSUE TITLE
Icons module not found

### ISSUE THREAD

**Issue by Mimetis** [OfficeDev/msteams-ui-components#139]
Hi teams;
I'm just trying your amazing components on a new project, but i'm facing a problem:

```
./node_modules/msteams-ui-components-react/lib/buttons/icon.js
Module not found: Can't resolve '../../../msteams-ui-icons/react/lib/index' in 'C:\PROJECTS\REACT\test01\my-app\node_modules\msteams-ui-components-react\lib\buttons'
```

Actually, here is my code. I just add a simple button

``` JS

class App extends React.Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>

        <PrimaryButton onClick={() => alert("You clicked me.")}>Click Me!</PrimaryButton>
      </div>
    );
  }
}
```

**Comment by MattSFT** [comment]
Try version 0.4.3. I think I introduced a bug in 0.4.4. Will fix in 0.4.5

**Comment by MattSFT** [comment]
Ok I just published version 0.4.5 that does not have this issue.

**Comment by Mimetis** [comment]
I have an other error, now

![image](https://user-images.githubusercontent.com/4592555/35692679-420899ea-077c-11e8-9a22-904d8a06194d.png)

**Comment by MattSFT** [comment]
We list typestyle as a peer dependency so it doesn't get auto installed. Do a npm install typestyle

**Comment by Mimetis** [comment]
To be sure, you can reproduce my beahvior.

I have created a new React application, using the TypeScript skeleton :

`create-react-app app02 --scripts-version=react-scripts-ts`

Then I just add the **msteams** components:

`npm install msteams-ui-components-react`

Then a pretty straightforward code:

```
import * as React from 'react';
import './App.css';
import { PrimaryButton } from "msteams-ui-components-react";

const logo = require('./logo.svg');

class App extends React.Component {
  render() {
    return (
      <div className="App">
        <header className="App-header">
          <img src={logo} className="App-logo" alt="logo" />
          <h1 className="App-title">Welcome to React</h1>
        </header>
        <p className="App-intro">
          To get started, edit <code>src/App.tsx</code> and save to reload.
        </p>
        <PrimaryButton onClick={() => alert('You clicked me.')}>Click Me!</PrimaryButton>
      </div>
    );
  }
}

export default App;

```

Then `npm start`

My package.json file, fyi:

```json
{
  "name": "app02",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "msteams-ui-components-react": "^0.4.5",
    "react": "^16.2.0",
    "react-dom": "^16.2.0",
    "react-scripts-ts": "2.13.0"
  },
  "scripts": {
    "start": "react-scripts-ts start",
    "build": "react-scripts-ts build",
    "test": "react-scripts-ts test --env=jsdom",
    "eject": "react-scripts-ts eject"
  },
  "devDependencies": {
    "@types/jest": "^22.1.1",
    "@types/node": "^9.4.0",
    "@types/react": "^16.0.36",
    "@types/react-dom": "^16.0.3",
    "typescript": "^2.7.1"
  }
}
```

**Comment by Mimetis** [comment]
I had to install two packages to be able to run the application:
```
npm install typestyle
npm install @types/prop-types
```
Finally, the project started, but now, I have this weird error, on runtime:

![image](https://user-images.githubusercontent.com/4592555/35693205-b9ecde34-077d-11e8-8e5d-771ab49be4bb.png)

**Comment by MattSFT** [comment]
You are missing the Context element; <TeamsComponentContext>must be defined as a parent of all other teams components:

https://www.npmjs.com/package/msteams-ui-components-react

Check out that link and notice the render() function of the SimplePage class
render() {
    return (
      <TeamsComponentContext
        fontSize={this.state.fontSize}
        theme={this.state.theme}>
        <PrimaryButton onClick={() => alert("You clicked me!")}>Click Me!</PrimaryButton>
      </TeamsComponentContext>
    );
  }

**Comment by MattSFT** [comment]
Also, if you want to handle theme change events from teams you can grab this code:

```
componentWillMount() {
    // If you are deploying your site as a MS Teams static or configurable tab, you should add ?theme={theme} to
    // your tabs URL in the manifest. That way you will get the current theme on start up (calling getContext on
    // the MS Teams SDK has a delay and may cause the default theme to flash before the real one is returned).
    this.updateTheme(this.getQueryVariable('theme'));
    this.setState({
      fontSize: this.pageFontSize(),
    });
 
    // If you are not using the MS Teams web SDK, you can remove this entire if block, otherwise if you want theme
    // changes in the MS Teams client to propogate to the page, you should leave this here.
    if (this.inTeams()) {
      microsoftTeams.initialize();
      microsoftTeams.registerOnThemeChangeHandler(this.updateTheme);
    }
  }
```

**Comment by Mimetis** [comment]
Thx !
Eventually, it works :)

Thx for your quick answers.
