### ISSUE TITLE
Implement <IconButton/> as shown in BasicElements.pdf

### ISSUE THREAD

**Issue by benpolinsky** [OfficeDev/msteams-ui-components#177]
Hi,

Is there a way to implement an `<IconButton />` as shown here: https://github.com/OfficeDev/msteams-ui-components/blob/master/docs/design/MicrosoftTeams-BasicElements.pdf ? I'm referring to the primary/secondary/tertiary flavors.

As far as I can tell, there are only two variations to each Icon, default and disabled, with the disabled variant being greyed-out.  

Thanks.

**Comment by MattSFT** [comment]
We only support the tertiary icon button at the moment.

The relevant styles are here: https://github.com/OfficeDev/msteams-ui-components/blob/master/msteams-ui-styles-core/src/components/icon-button.ts
And the React binding is here: https://github.com/OfficeDev/msteams-ui-components/blob/master/msteams-ui-components-react/src/buttons/icon.tsx

It shouldn't be too hard to add the other flavors but we are a bit swamped with other work at the moment.

**Comment by benpolinsky** [comment]
All good - appreciate the quick response. Just waned to make sure I wasn't missing anything.
