### ISSUE TITLE
this.inTeams() always return false?

### ISSUE THREAD

**Issue by paul-cheung** [OfficeDev/msteams-ui-components#180]
i am using ngrok to debug my localhost sample project. but `this.inTeams()` always return false when the url was set to MS Teams.

**Comment by MattSFT** [comment]
the inTeams() check is kind of naïve, it returns true if the current window is not the top window (i.e. your window is being IFramed)

**Comment by paul-cheung** [comment]
@MattSFT but when i remove the if(this.inTeams()) check statement, code running as the following steps.
1. microsoftTeams.initialize(); [ok]
2. microsoftTeams.getContext((context: microsoftTeams.Context) => { alert('test'); }); [i am not getting a 'test' alert]
any help?

**Comment by MattSFT** [comment]
I think teams blocks alerts in general, try console.log ?

**Comment by paul-cheung** [comment]
is there a way like Developer tools of browser in Teams that i can use to check whether console.log work or not?

**Comment by MattSFT** [comment]
If you are in the developer preview ring, you can right click on the teams task tray icon and open the developer tools that way. The option is only there if your tab is loaded

**Comment by MattSFT** [comment]
![image](https://user-images.githubusercontent.com/29067893/44162809-3de80100-a076-11e8-92af-0dd37dcd1e08.png)
You will have to restart your teams client AFTER entering developer preview mode for this option to be available.

**Comment by paul-cheung** [comment]
what is 'developer preview ring'? there is no menu called 'Open DevTools' here.

**Comment by MattSFT** [comment]
Here are docs on getting into the developer preview: https://docs.microsoft.com/en-us/microsoftteams/platform/resources/dev-preview/developer-preview

The screenshot is a little outdated but the menu still exists on your profile picture in teams. Once in developer preview, make sure to restart the teams client and then the open devtools option should show up
