### ISSUE TITLE
componentWillMount is deprecated

### ISSUE THREAD

**Issue by JSteunou** [OfficeDev/msteams-ui-components#182]
Please update your components with latest React best practice: componentWillMount is or will be deprecated (depending on the version your are using)

* https://medium.com/@baphemot/whats-new-in-react-16-3-d2c9b7b6193b
* https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html

This is related to @jialic issue #160

**Comment by MattSFT** [comment]
This should be resolved in the latest version 0.8.1 of the components library
