### ISSUE TITLE
Example docs

### ISSUE THREAD

**Issue by RobPethick** [OfficeDev/msteams-ui-components#183]
I notice some examples in the gh-pages folder - is this released to some github pages at all? Or is this still in dev?

**Comment by MattSFT** [comment]
https://officedev.github.io/msteams-ui-components/

**Comment by RobPethick** [comment]
Thanks! We should add this link to the readme pages so it is a bit clearer

**Comment by MattSFT** [comment]
Sure. We haven't really been supporting this library too much lately mostly due to our efforts being applied to providing a teams theme to this library https://github.com/stardust-ui/react

**Comment by MattSFT** [comment]
the problem with that is lib is that it isn't yet ready to be used in production. We've used this one to build a few apps already

**Comment by RobPethick** [comment]
Ah that makes a lot of sense - I'll keep using this for now but I look forward to a theme to a larger library
