### ISSUE TITLE
Wrong text color on dropdown label with high contrast theme

### ISSUE THREAD

**Issue by jimmyfortinx** [OfficeDev/msteams-ui-components#189]
When using the _High contrast_ theme with a Dropdown from this library, Dropdown's labels are the same color than the background (black), so it is impossible to read the label at all. On other themes labels are readable.

<img width="251" alt="screen shot 2019-01-07 at 9 07 59 am" src="https://user-images.githubusercontent.com/16029436/50772700-aa011680-125c-11e9-84b4-1fc8a9f08634.png">

There is same view, but in other themes:
<img width="253" alt="screen shot 2019-01-07 at 9 07 35 am" src="https://user-images.githubusercontent.com/16029436/50772728-beddaa00-125c-11e9-9392-51c6f1803717.png">

<img width="260" alt="screen shot 2019-01-07 at 9 07 48 am" src="https://user-images.githubusercontent.com/16029436/50772721-bd13e680-125c-11e9-98fe-b5489a6f6d87.png">

This issue is visible from the **App Studio** when going on the _Control Library_ and selecting the _Dropdowns_ category.

**Comment by MattSFT** [comment]
Fixed in this PR: https://github.com/OfficeDev/msteams-ui-components/pull/190

**Comment by MattSFT** [comment]
Fixed in msteams-ui-styles-core v0.8.1
