### ISSUE TITLE
Bundle Error while installing "msteams-ui-components-react" in my SPFX webpart.

### ISSUE THREAD

**Issue by pk091990** [OfficeDev/msteams-ui-components#194]
I'm currently working on SPFX 1.7.1-plusbeta version and deploying SPFX webpart to Microsoft Teams as a tab. I've run npm i msteams-ui-components-react (current version and tried with older version also) and npm install typestyle to get Teams Theme specific context. However  I'm getting below errors on bundle command. Please help !

[15:16:46] Error - [webpack] 'dist':
./node_modules/msteams-ui-icons-core/fonts/TeamsAssets-Light.woff2
Module parse failed: C:\Teams\node_modules\msteams-ui-icons-core\fonts\TeamsAssets-Light.woff2 Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/msteams-ui-icons-core/lib/index.js 537:20-63
 @ ./node_modules/msteams-ui-icons-react/lib/index.js
 @ ./node_modules/msteams-ui-components-react/lib/dropdown/dropdown.js
 @ ./node_modules/msteams-ui-components-react/lib/dropdown/index.js
 @ ./node_modules/msteams-ui-components-react/lib/index.js
 @ ./lib/webparts/polls/components/Main/Main.js
 @ ./lib/webparts/polls/components/Main/index.js
 @ ./lib/webparts/polls/PollsWebPart.js
./node_modules/msteams-ui-icons-core/fonts/TeamsAssets-Regular.woff2
Module parse failed: C:\Teams\node_modules\msteams-ui-icons-core\fonts\TeamsAssets-Regular.woff2 Unexpected character ' ' (1:4)
You may need an appropriate loader to handle this file type.
(Source code omitted for this binary file)
 @ ./node_modules/msteams-ui-icons-core/lib/index.js 550:20-65
 @ ./node_modules/msteams-ui-icons-react/lib/index.js
 @ ./node_modules/msteams-ui-components-react/lib/dropdown/dropdown.js
 @ ./node_modules/msteams-ui-components-react/lib/dropdown/index.js
 @ ./node_modules/msteams-ui-components-react/lib/index.js
 @ ./lib/webparts/polls/components/Main/Main.js
 @ ./lib/webparts/polls/components/Main/index.js
 @ ./lib/webparts/polls/PollsWebPart.js

**Comment by MattSFT** [comment]
Add this loader to your webpack:

```json
{
  test: /\.(png|svg|jpg|gif|woff|woff2|eot|ttf|otf)$/,
  use: 'file-loader'
}
```

Like this: https://github.com/OfficeDev/msteams-ui-components/blob/fb37dfdcf537c572b1b030f6bafb1e0b116c6ebf/gh-pages/webpack.common.js#L21

**Comment by rabwill** [comment]
> Add this loader to your webpack:
> [msteams-ui-components/gh-pages/webpack.common.js](https://github.com/OfficeDev/msteams-ui-components/blob/fb37dfdcf537c572b1b030f6bafb1e0b116c6ebf/gh-pages/webpack.common.js#L20-L23)
> 
> Lines 20 to 23 in [fb37dfd](/OfficeDev/msteams-ui-components/commit/fb37dfdcf537c572b1b030f6bafb1e0b116c6ebf)
> 
>  { 
>    test: /\.(png|svg|jpg|gif|woff|woff2|eot|ttf|otf)$/, 
>    use: 'file-loader', 
>  }

Worked like a charm !

**Comment by paddotk** [comment]
This didn't work for me; when I add this to webpack.config.js I get the error
```
ERROR in ./node_modules/msteams-ui-icons-core/lib/index.js
Module not found: Error: Can't resolve 'file-loader' in <project path>
```
Any ideas?

**Comment by Ravikadri-zz** [comment]
> > Add this loader to your webpack:
> > [msteams-ui-components/gh-pages/webpack.common.js](https://github.com/OfficeDev/msteams-ui-components/blob/fb37dfdcf537c572b1b030f6bafb1e0b116c6ebf/gh-pages/webpack.common.js#L20-L23)
> > Lines 20 to 23 in [fb37dfd](/OfficeDev/msteams-ui-components/commit/fb37dfdcf537c572b1b030f6bafb1e0b116c6ebf)
> > {
> > test: /.(png|svg|jpg|gif|woff|woff2|eot|ttf|otf)$/,
> > use: 'file-loader',
> > }
> 
> Worked like a charm !

@rabwill , maybe a basic question. where exactly you add this line. I don't see any msteams-ui-components/gh-pages/webpack.common.js path. Can you give some hints.
![image](https://user-images.githubusercontent.com/9435596/103140919-8f224980-46a1-11eb-86f7-33fe287d63ff.png)
