### ISSUE TITLE
Font not load

### ISSUE THREAD

**Issue by andreatosato** [OfficeDev/msteams-ui-components#201]
Hi, I'm studing MS Teams development.
I start with this guide: https://docs.microsoft.com/en-us/microsoftteams/platform/get-started/app-studio-component-library

I add this NPM:

- npm install --save typestyle && npm install --save msteams-ui-components-react
- npm install --save msteams-ui-icons-react

This is my sample:
https://stackblitz.com/edit/react-teams

My errors:
_**Import error, can't find files:
../fonts/TeamsAssets-Light.eot
../fonts/TeamsAssets-Light.woff
../fonts/TeamsAssets-Light.woff2
../fonts/TeamsAssets-Light.ttf
../fonts/TeamsAssets-Light.svg
../fonts/TeamsAssets-Regular.eot
../fonts/TeamsAssets-Regular.woff
../fonts/TeamsAssets-Regular.woff2
../fonts/TeamsAssets-Regular.ttf
../fonts/TeamsAssets-Regular.svg**_

What am I doing wrong?

**Comment by andreatosato** [comment]
After create new React application, I have this error:
**Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.**

My index.js
```import React, {Component} from 'react';
import { render } from 'react-dom';
import { TeamsComponentContext, ThemeStyle } from 'msteams-ui-components-react';
import './index.css';

class App extends Component {
  
    render() {
      return (
       <TeamsComponentContext
              fontSize={16}
              theme={ThemeStyle.Light}
          />
      );
    }
  }
export default App;
render(<App />, document.getElementById('root'));
```

**Comment by MattSFT** [comment]
I'm not sure what your exact issue is but take a look at these files for reference:
https://github.com/OfficeDev/msteams-ui-components/blob/master/gh-pages/src/index.tsx
https://github.com/OfficeDev/msteams-ui-components/blob/master/gh-pages/webpack.common.js
