### ISSUE TITLE
Dropdown always selects first option when opened

### ISSUE THREAD

**Issue by KarlPurk** [OfficeDev/msteams-ui-components#202]
The dropdown component does not allow the current selected option to be specified, this results in the first option always being selected by default.   For example:

![image](https://user-images.githubusercontent.com/1528469/59763215-039c5100-9291-11e9-9c5c-c4ee15eb05ff.png)

In the above image, we can see that the user previously selected the "30 minute" option, but when they opened the dropdown again the first (wrong) option is selected.  I don't see any way that I can change this behaviour using the dropdown component props.

**Comment by MattSFT** [comment]
This library will shortly be deprecated in favor of Stardust UI.
If you are starting an app from scratch, consider using https://stardust-ui.github.io/react/ instead.

**Comment by KarlPurk** [comment]
Thanks @MattSFT.  Unfortunately we're already well into development with this app and switching at this stage would be more effort than it's worth.  I've added this functionality in a private fork.

**Comment by MattSFT** [comment]
We’ll take a pull request if you submit it. We also have a few projects that still rely on these libs heavily.

**Comment by KarlPurk** [comment]
Happy to submit a PR but not sure if you'd want it.  

For our app, the original behaviour, were the dropdown defaults to the first option, didn't make sense so we removed it.  

In our fork, if you specify a selected value then that option will be selected.  If you do not specify a selected value no option is selected.  If you want the first option to be selected you would need to explicitly specify that option as selected.

**Comment by MattSFT** [comment]
I think thats fine. Send it over.
