### ISSUE TITLE
Component Documentation

### ISSUE THREAD

**Issue by damienestewart** [OfficeDev/msteams-ui-components#205]
Hi Team,

Is there any documentation/demos that shows how to use some of the components like panels or surfaces?

**Comment by MattSFT** [comment]
Not really. For surface, just drop one at the top level of the page, it gives background and some font css properties.

You can see a panel in action here:
https://github.com/OfficeDev/msteams-ui-components/blob/80ed16e2fe4abed31fd002b93ebe2130d40b6ae2/gh-pages/src/sidebar/index.tsx#L90-L115

**Comment by MattSFT** [comment]
gh-pages folder is the website that renders this:
https://officedev.github.io/msteams-ui-components/#/

**Comment by damienestewart** [comment]
Awesome, thanks a lot @MattSFT! Do you know offhand if Office UI Fabric styles/icons can be used with these styles simultaneously, or if it would be a bad idea to mix these? At the moment, I'm mainly interested in leveraging Fabric's grid layout (unless I can also use msteams-ui-components styles to control the layout). My bad for the noob question!

Also heads up, it looks like quite a bit of the [icon table](https://officedev.github.io/msteams-ui-components/#/icons) is being cut off.

**Comment by MattSFT** [comment]
Ideally, you would move towards this library: https://github.com/stardust-ui/react.

We currently have a very low level of investment in the msteams-ui-components packages and are trying to deprecate in favor of stardust. Having said that, there isn't 100% parity between the two and a lot of our developer tools still point and are built from the msteams-ui-components library (like App Studio https://aka.ms/InstallTeamsAppStudio).

**Comment by damienestewart** [comment]
I'll definitely give stardust a try. Thanks for all the help and info!

**Comment by lucasm107** [comment]
> Ideally, you would move towards this library: https://github.com/stardust-ui/react.
> 
> We currently have a very low level of investment in the msteams-ui-components packages and are trying to deprecate in favor of stardust. Having said that, there isn't 100% parity between the two and a lot of our developer tools still point and are built from the msteams-ui-components library (like App Studio https://aka.ms/InstallTeamsAppStudio).

Hi @MattSFT ! Have you see any example like the gh-pages folder but using stardust-ui? because I need the theme style change function like the msteams-ui-components library.

Thanks!
