### ISSUE TITLE
[Question] What is the status of this project?

### ISSUE THREAD

**Issue by kafka-yu** [OfficeDev/msteams-ui-components#213]
Hi Team,

Is there anyone to give the current status of this project?
Is it keeping developing?
What's the relationship with the UI lib: FluentUI? https://github.com/OfficeDev/office-ui-fabric-react/tree/master/packages/fluentui

Thanks.

**Comment by ig-jb** [comment]
@kafka-yu Just an observation -- I believe this project is effectively dead and succeeded by FluentUI Northstar - https://github.com/microsoft/fluentui/blob/master/packages/fluentui/README.md

FluentUI and FluentUI Northstar will merge to be just FluentUI at a later date.

**Comment by kafka-yu** [comment]
Thanks for the clarification! @ig-jb
